### ISSUE TITLE
npm run register-contract  (Hyper ledger besu setup)

### ISSUE THREAD

**Issue by malaoui79** [ConsenSys/quorum-dev-quickstart#17]
npm run register-contract do not work : 
******************************
(base) ➜  quorum-test-hlb npm run register-contract

> codefi-orchestrate-quick-start@2.3.0 register-contract /Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb
> dotenv ts-node src/register-contract

Error: 14 UNAVAILABLE: could not create repository
    at Object.callErrorFromStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
    at Object.onReceiveStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
    at Http2CallStream.outputStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call-stream.ts:230:22)
    at Http2CallStream.maybeOutputStatus (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call-stream.ts:280:14)
    at Http2CallStream.endCall (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call-stream.ts:263:12)
    at Http2CallStream.handleTrailers (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call-stream.ts:412:10)
    at ClientHttp2Stream.<anonymous> (/Users/simo-mac/workspace/cultydata/blockchain/quorum/quorum-test-hlb/node_modules/@grpc/grpc-js/src/call-stream.ts:467:16)
    at ClientHttp2Stream.emit (events.js:314:20) {
  code: 14,
  details: 'could not create repository',
  metadata: Metadata {
    internalRepr: Map(2) {
      'content-type' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  }
}
******************************

Seems that postgres data base is not initialized with the right schema. In deps_postgres-contract-registry_1 we have this : 

**************
2020-10-02 13:21:10.060 UTC [93] ERROR: relation "repositories" does not exist at character 18

2020-10-02 13:21:10.060 UTC [93] STATEMENT: SELECT "id" FROM repositories AS "repository_model" WHERE (name = 'Counter')
**************

Thanks for your help.

**Comment by malaoui79** [comment]
Worked after all the container have been restarted !!

**Comment by malaoui79** [comment]
In fact, after some investigation, there is a race condition at startup, the init migration, migration container and postgres instance container are not well scheduled so we can start migration before the init migration script .... could be fixed by making migration script waiting for init termination.

**Comment by joshuafernandes** [comment]
@julien-marchand reckon we add this in if this is still a problem?

**Comment by joshuafernandes** [comment]
closing this one for lack of activity, please re open if this is an issue still
