### ISSUE TITLE
Error: types.forEach is not a function

### ISSUE THREAD

**Issue by mfolnovic** [ConsenSys/quorum-dev-quickstart#183]
While running `npm run private-transaction` (also happens with public-transaction), I get an error:

```
> @consensys-software/smart_contracts@1.0.0 private-transaction
> node scripts/private_tx.js

TypeError: types.forEach is not a function
    at ABICoder.mapTypes (/home/mfolnovic/dev/projects/besu-instance/smart_contracts/privacy/node_modules/web3-eth-abi/lib/index.js:132:11)
    at ABICoder.encodeParameters (/home/mfolnovic/dev/projects/besu-instance/smart_contracts/privacy/node_modules/web3-eth-abi/lib/index.js:92:18)
    at createContract (/home/mfolnovic/dev/projects/besu-instance/smart_contracts/privacy/scripts/private_tx.js:21:48)
    at main (/home/mfolnovic/dev/projects/besu-instance/smart_contracts/privacy/scripts/private_tx.js:87:3)
    at Object.<anonymous> (/home/mfolnovic/dev/projects/besu-instance/smart_contracts/privacy/scripts/private_tx.js:111:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

My steps are:

- `./run.sh`
- `cd smart_contracts/privacy`
- `npm install`
- `npm run compile`
- `npm run private-transaction`

I've determined that it happens since version 0.0.66. Version 0.0.65 is last version that works for me.

I'm running `npx quorum-dev-quickstart@xyz` (where xyz is version).

**Comment by macfarla** [comment]
@mfolnovic do you get the same error with the latest quickstart ie 0.0.68?
