### ISSUE TITLE
Error on Explorer/Contract Page

### ISSUE THREAD

**Issue by 4-Mix** [ConsenSys/quorum-dev-quickstart#197]
Compiling example code with any version of Solidity causes an error

![image](https://user-images.githubusercontent.com/94184698/183861110-7adba5e0-4db2-46f9-88c0-3be12ee2cebc.png)

540-6adbe5fe9aefc9d0.js:1          POST http://localhost:25000/explorer/api/contractCompile 500 (Internal Server Error)
(anonimo) @ 540-6adbe5fe9aefc9d0.js:1
e.exports @ 540-6adbe5fe9aefc9d0.js:1
e.exports @ 540-6adbe5fe9aefc9d0.js:1
l.request @ 540-6adbe5fe9aefc9d0.js:1
(anonimo) @ 540-6adbe5fe9aefc9d0.js:1
(anonimo) @ contracts-4990bcde34a66324.js:1
s @ main-75222ed780d2497a.js:1
(anonimo) @ main-75222ed780d2497a.js:1
P.forEach.e.<computed> @ main-75222ed780d2497a.js:1
V @ contracts-4990bcde34a66324.js:1
i @ contracts-4990bcde34a66324.js:1
(anonimo) @ contracts-4990bcde34a66324.js:1
(anonimo) @ contracts-4990bcde34a66324.js:1
(anonimo) @ contracts-4990bcde34a66324.js:1
$e @ framework-e283f07682b6ab3d.js:1
Ye @ framework-e283f07682b6ab3d.js:1
(anonimo) @ framework-e283f07682b6ab3d.js:1
Nr @ framework-e283f07682b6ab3d.js:1
Tr @ framework-e283f07682b6ab3d.js:1
(anonimo) @ framework-e283f07682b6ab3d.js:1
Ie @ framework-e283f07682b6ab3d.js:1
(anonimo) @ framework-e283f07682b6ab3d.js:1
Fr @ framework-e283f07682b6ab3d.js:1
Jt @ framework-e283f07682b6ab3d.js:1
Zt @ framework-e283f07682b6ab3d.js:1
t.unstable_runWithPriority @ framework-e283f07682b6ab3d.js:1
Ql @ framework-e283f07682b6ab3d.js:1
Me @ framework-e283f07682b6ab3d.js:1
Xt @ framework-e283f07682b6ab3d.js:1
contracts-4990bcde34a66324.js:1 Error: Request failed with status code 500
    at e.exports (540-6adbe5fe9aefc9d0.js:1:14485)
    at e.exports (540-6adbe5fe9aefc9d0.js:1:16927)
    at XMLHttpRequest.w (540-6adbe5fe9aefc9d0.js:1:9076)

**Comment by joshuafernandes** [comment]
Hello @4-Mix can you please tell us what version of the quickstart you are using and which client you are using. Ideally steps for us to replicate what you are seeing please

**Comment by joshuafernandes** [comment]
On ver 0.0.75, I am unable to reproduce this using goquorum to compile the `simpleStorage` contract for public contract deploy. I've tried a few different versions of the compiler (>0.8.13) and all worked fine. You may need to wait a min or two after the quickstart containers come up for all the nodes to come up and the explorer to work right

![image](https://user-images.githubusercontent.com/3722503/188434145-546a6b0b-51ea-4d89-b0b7-395925a9db39.png)

**Comment by joshuafernandes** [comment]
Closing for lack of activity, Please feel free to re open if this is an issue and include the version you are using and steps to reproduce

**Comment by joshuafernandes** [comment]
Hi @torestin 

You can use something like truffle here https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/using-the-quickstart/#deploy-your-own-dapp

or natively with solc 
https://consensys.net/docs/goquorum/en/latest/tutorials/contracts/deploying-contracts/
