### ISSUE TITLE
error after running node deployContract.js

### ISSUE THREAD

**Issue by Bellomi** [Consensys/quorum-dev-quickstart#261]
Everything in the tutorial goes well untill I run the command node deployContract.js and get the response:

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at request.onreadystatechange (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/home/vntlibe/Desktop/Code/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

This example requires ONCHAIN privacy to be DISABLED. 
Check config for ONCHAIN privacy groups.

If anyone could help. I apreciate it.

**Comment by Bellomi** [comment]
My dock container is not running

**Comment by joshuafernandes** [comment]
Hello Bellomi,

Please refer to the [Readme](https://github.com/Consensys/quorum-dev-quickstart#troubleshooting) for how to solve the io exception

Cheers

**Comment by Bellomi** [comment]
where exactly should I alter this information in the docker-compose.yaml?
I added in this part:

x-besu-def: &besu-def
  restart: "on-failure"
  **image: hyperledger/besu:${BESU_VERSION:-latest}
  user: $(id -u):$(id -g)**
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    
    
    and it did not work.

**Comment by joshuafernandes** [comment]
Hello Bellomi,

This is the context of it https://github.com/Consensys/quorum-dev-quickstart/issues/131. Im not sure what user id's you have present on your machine or what the default is or how it's been setup. The besu container however runs as user 1000, and we discourage the use of the `root` user. 

It is however impossible to debug without steps to reproduce this issue. Could you please post details of your environment as well as the steps you took to get up and running and any commands you've used

Cheers

**Comment by Bellomi** [comment]
Hello,
I follow all the steps and when I am at node scripts/private_tx.js I get the error:
Creating contract...
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at request.onreadystatechange (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/home/vntlibe/quorum-test-network/smart_contracts/privacy/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21).

**Comment by joshuafernandes** [comment]
Hello @Bellomi ,

I;m not able to reproduce your issue. As above, could you please post: details of your environment as well as the steps you took to get up and running and any commands you've used

**Comment by Bellomi** [comment]
It turned out that after changing the user and group id I still got the error because the opt/besu/data was trying to be acessed and as Iḿ not the root nor anyone should be for security reasons, it was returning the error opt/besu/data not found.
So I added a different data directory for each node and set inside the run.sh also.

**the run.sh is like:**
_create log folders with the user permissions so it won't conflict with container permissions_
mkdir -p logs/besu logs/quorum logs/tessera **data1 data2 data3 data4 rpcnodedata member1besudata member2besudata member3besudata**

and the docker-compose.yml:
---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  user: "1002:1002"
......
 
x-tessera-def:
  &tessera-def
  user: "1002:1002"
  ....................

services:

  validator1:
    << : *besu-def
 .......
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./data1:/opt/besu/data**
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
   ....
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./data2:/opt/besu/data**
   ....

  validator3:
    << : *besu-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
  ....
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      - ./data3:/opt/besu/data
    ....
  validator4:
    << : *besu-def
   ......
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./data4:/opt/besu/data**
  .....

  rpcnode:
   ...
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./rpcnodedata:/opt/besu/data**
......

  member1besu:
 .....
      - ./config/besu/:/config
      - ./config/nodes/member1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./member1besudata:/opt/besu/data**
 ....

  member2besu:
  .....
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/member2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./member2besudata:/opt/besu/data**
 ....
  member3besu:

......
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/member3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
      **- ./member3besudata:/opt/besu/data**
    depends_on:
      - validator1
      - member3tessera 

 .......
