### ISSUE TITLE
Migration error on deploy pet-shop dapp

### ISSUE THREAD

**Issue by bcuestav** [ConsenSys/quorum-dev-quickstart#48]
Hi,

I'm getting an error when deploy pet-shop dapp in HL Besu test network. The network deploy successfully but when I run './run_dapp.sh' script, get this error:

```
...
...
Compiling your contracts...
===========================
> Compiling ./contracts/Adoption.sol
> Compiling ./contracts/Migrations.sol
> Artifacts written to /Users/benitojcv/ULL/quorum-dev-quickstart/quorum-test-network/dapps/pet-shop/pet-shop-box/build/contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'quickstartWallet'
> Network id:      2018
> Block gas limit: 16234336 (0xf7b760)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Internal error.

    at /Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:74:1)
    at Migration._load (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/Users/benitojcv/.nvm/versions/node/v12.21.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.5 (core: 5.2.5)
Node v12.21.0

```

I remember do it some times ago, and it worked fine!

My environment is:

- OS X 10.15.7 (I try in Linux Ubuntu 18.04 with the same error)
- Docker version 20.10.5
- Node v12.21.0 (I try with other versions too)
- npm 6.14.11
- Truffle v5.2.5

**Comment by joshuafernandes** [comment]
Hi @bcuestav 

I belive this was due to an issue with the some changes metamask and truffle had made recently, #49 has fixed those and I've just spun up the DApp and used it without issue.

```

Compiling your contracts...
===========================
> Compiling ./contracts/Adoption.sol
> Compiling ./contracts/Migrations.sol
> Artifacts written to /home/jfernandes/workspace/quorum-dev-quickstart/quorum-test-network/dapps/pet-shop/pet-shop-box/build/contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'quickstartWallet'
> Network id:      1337
> Block gas limit: 16234336 (0xf7b760)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x859cc309396ab16b8095c4aee991945a78b12963d752c57518c6507a78bbaa47
   > Blocks: 0            Seconds: 0
   > contract address:    0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
   > block number:        472
   > block timestamp:     1618179716
   > account:             0x627306090abaB3A6e1400e9345bC60c78a8BEf57
   > balance:             89999.9955689
   > gas used:            221555 (0x36173)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0044311 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.0044311 ETH


2_deploy_contracts.js
=====================

   Deploying 'Adoption'
   --------------------
   > transaction hash:    0x5624454e63aab002f0deb9a29885c2df1090a390235327ed084c38a0ebb504aa
   > Blocks: 0            Seconds: 0
   > contract address:    0x345cA3e014Aaf5dcA488057592ee47305D9B3e10
   > block number:        474
   > block timestamp:     1618179720
   > account:             0x627306090abaB3A6e1400e9345bC60c78a8BEf57
   > balance:             89999.98993064
   > gas used:            239915 (0x3a92b)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0047983 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.0047983 ETH


Summary
=======
> Total deployments:   2
> Final cost:          0.0092294 ETH


Using network 'quickstartWallet'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



  0 passing (1ms)

Sending build context to Docker daemon  467.7MB
Step 1/5 : FROM node:12.14.1-stretch-slim
12.14.1-stretch-slim: Pulling from library/node
619014d83c02: Pull complete 
8c5d9aed65fb: Pull complete 
aaabe8e9daf2: Pull complete 
f7567fa7b9f3: Pull complete 
a989ed5f800b: Pull complete 
Digest: sha256:59ac2f2c3a0c490d8424306032f9b638f5ea83327ffaf23c66490e0026d1a000
Status: Downloaded newer image for node:12.14.1-stretch-slim
 ---> 2f7e25ad14ea
Step 2/5 : EXPOSE 3001
 ---> Running in a012d94d137b
Removing intermediate container a012d94d137b
 ---> 457daca90bce
Step 3/5 : WORKDIR /app
 ---> Running in fbb504a04632
Removing intermediate container fbb504a04632
 ---> 1cb30d00bb5f
Step 4/5 : COPY . /app
 ---> 10dd5e5ecd9e
Step 5/5 : CMD npm run dev
 ---> Running in e2a864d0b2a3
Removing intermediate container e2a864d0b2a3
 ---> dcaa7c71ebca
Successfully built dcaa7c71ebca
Successfully tagged quorum-dev-quickstart_pet_shop:latest
03f2cfc5343a9395e9e6f5e20a5463dca62b1dafe784bae0105ca5f924376a00

```

Running the DApp also let me adopt a pet fine 
![image](https://user-images.githubusercontent.com/3722503/114323591-3a7bdf00-9b69-11eb-9fa8-4efc4b166278.png)


Are you able to test this again please and let me know if you have an issue with it? My system has Ubuntu 20.04 with node 14.16 and npm 6.14.11

**Comment by bcuestav** [comment]
Ok! It works now! It was the problem of the chainId!

By the way, the chainId remains to be changed in `smart_contracts/scripts/depoy.js`. I send a pull request!
